---
- name: Install and setup web application using ansible automation
  hosts: all
  tasks:
    
    - name: Install httpd package
      yum:
         name: httpd
         state: latest

    - name: copy source in var/www/html
      copy:
        src: ./src/
        dest: /var/www/html
        force: yes

    - name: start httpd service
      service:
         name: httpd
         state